package entities;
// Generated Oct 29, 2019 11:14:08 AM by Hibernate Tools 4.3.1

/**
 * Sanpham generated by hbm2java
 */
public class Sanpham implements java.io.Serializable {

    private String masp;
    private String tensp;
    private String gia;
    private boolean status;

    public Sanpham() {
    }

    public Sanpham(String masp) {
        this.masp = masp;
    }

    public Sanpham(String masp, String tensp, String gia) {
        this.masp = masp;
        this.tensp = tensp;
        this.gia = gia;
    }

    public String getMasp() {
        return this.masp;
    }

    public void setMasp(String masp) {
        this.masp = masp;
    }

    public String getTensp() {
        return this.tensp;
    }

    public void setTensp(String tensp) {
        this.tensp = tensp;
    }

    public String getGia() {
        return this.gia;
    }

    public void setGia(String gia) {
        this.gia = gia;
    }

    public boolean isStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }


}
